// Package climate is the dynamic-terrain driver: a pure, deterministic transform over a coarse
// climate grid (Moisture + Temperature in °C + Terrain) plus a world-uniform Wind.
//
// Forbidden imports (one-way wiring): engine/space/navmap, engine/kernel/worldtime,
// engine/mind/gates. (climate IS allowed to import expr — it is L0.)
//
// D12 determinism invariants:
//   - All randomness comes from the injected *rng.RNG, drawn in fixed order (rain → wind).
//   - No time.Now(), no global rand, no wall-clock.
//   - Grid iteration is always Y-major then X (sorted GridCell order).
//   - Step is a pure function: it never mutates prev, Rules, or Forcing.
package climate

import (
	"fmt"
	"math"

	"github.com/dogring/bdg/engine/kernel/core"
)

const (
	moistureMin      = 0.0
	moistureMax      = 1.0
	windMin          = 0.0
	windMax          = 1.0
	cellCenterOffset = 0.5
)

// ── Identity & state ─────────────────────────────────────────────────────────

// GridCell is the integer index of a coarse climate cell. One climate cell spans many navmap
// cells. It is an internal index, never an agent position (D11). Distinct conceptually from
// navmap.Cell; world owns the climate-cell → navmap-cell mapping.
type GridCell struct{ X, Y int }

// CellState is the per-climate-cell dynamic state.
//   - Moisture    is normalized [0,1] (clamped). Rain raises it; evaporation (∝ Temperature°C) lowers it.
//   - Temperature is ACTUAL °C (CA3 RESOLVED option ii) and is NOT clamped — winter nights can be sub-zero.
//   - Terrain     is the current terrain type of this climate cell (drives transitions).
type CellState struct {
	Moisture    float64      // wetness ∈ [0,1] (clamped)
	Temperature float64      // °C (CA3) — NOT clamped; f(annual,daily,rain)
	Terrain     navTerrainID // current terrain type
}

// Wind is the world-uniform prevailing wind (CA2 RESOLVED option a) — a single scalar pair.
// Generated by Step, stored in State so resume is byte-identical (D12).
type Wind struct {
	Dir float64 // prevailing direction, radians ∈ [0,2π). §6 operand "wind.dir".
	Mag float64 // strength, normalized [0,1] (clamped). §6 operand "wind.mag".
}

// navTerrainID is the terrain-type identifier. Declared as core.Tag so climate does NOT import
// engine/space/navmap (one-way wiring; world bridges climate→navmap, RESOLVED #6).
type navTerrainID = core.Tag

// RainProcess is the seeded stochastic rain accumulator (1a). Captured in the snapshot so
// resume is byte-identical (D12). Exposed read-only for serialization + observability.
type RainProcess struct {
	Raining        bool    // currently raining
	RainEndsAtHour int64   // game-hour the current rain stops (valid iff Raining)
	PRain          float64 // accumulating per-game-hour rain probability (0 right after rain; rises each dry hour)
	HoursSinceRain int64   // game-hours since last rain ended (drives 10d expected / 30d hard cap)
}

// Config carries the climate-grid geometry + tuning RATES, injected by platform/config from
// content/climate.yaml. The 10-day expected / 30-day forced / 2–12h-duration SHAPE is fixed
// design in the formulas; only rates are content (D10).
type Config struct {
	// Coarse-grid geometry
	GridCols, GridRows int       // coarse-grid dimensions
	WorldMin, WorldMax core.Vec2 // continuous extent the coarse grid spans (world units)
	InitMoisture       float64   // starting Moisture ∈ [0,1]
	// InitMoistureAt is an OPTIONAL per-cell initial-moisture field (WG1-a stage 4:
	// water-proximity seeding — worldgen supplies it for generated terrain). nil ⇒ the
	// uniform InitMoisture (all existing fixtures/goldens unchanged). Sampled once at New
	// per cell centre, clamped to [0,1]; Restore ignores it (moisture round-trips from
	// the snapshot).
	InitMoistureAt  func(core.Vec2) float64
	InitTemperature float64 // starting Temperature in °C (CA3)

	// Rain process (1a; fixed 10d/30d/2–12h shape; only rates are content)
	RainProbPerHour  float64 // per-game-hour increment to PRain
	RainHardCapHours int64   // forced rain after this many dry game-hours (design value = 720)
	RainDurMinHours  int64   // rain duration lower bound (design value = 2)
	RainDurMaxHours  int64   // rain duration upper bound (design value = 12)
	MoistureRainRate float64 // Moisture gained per game-hour while raining

	// Evaporation (1a; re-based to °C, CA3)
	EvapBaseRate  float64 // base Moisture lost per dry game-hour (temperature-independent)
	EvapTempScale float64 // EXTRA Moisture lost per dry game-hour per °C of positive Temperature (per-°C units); max(0,T) floored

	// Temperature model (1b; °C additive composition, CA1/CA3)
	AnnualMid    float64 // °C annual midline
	AnnualAmp    float64 // °C annual amplitude; AnnualMid±AnnualAmp spans roughly −5…30 °C (CA1)
	AnnualPhase  float64 // φ radians — aligns the sin peak with summer YearFraction
	TempDayPeak  float64 // °C DELTA added at the daily peak (positive; e.g. afternoon)
	TempNightLow float64 // °C DELTA added at the daily trough (negative; e.g. pre-dawn)
	TempRainDrop float64 // °C reduction while raining (CA3)

	// Wind model (CA2; world-uniform directional random-walk on the per-step RNG fork)
	WindPrevailingDir float64 // radians [0,2π) — the direction Dir mean-reverts toward
	WindDirDrift      float64 // radians — per-step Gaussian random-walk step scale for Dir
	WindDirReversion  float64 // [0,1] — fraction Dir is pulled back toward WindPrevailingDir each step
	WindMagMean       float64 // [0,1] — mean magnitude
	WindMagNoise      float64 // Gaussian per-step magnitude-noise amplitude; resulting Mag clamped [0,1]
}

// Forcing is the per-step exogenous input. world builds it from the current Tick (live) or
// from a fixture (golden/scenario). Climate never reads a clock (D12).
type Forcing struct {
	HourOfDay    int     // [0,24) from worldtime.Clock.HourOfDay — drives the DAILY Temperature delta
	AbsHour      int64   // absolute game-hour count (worldtime), monotone — drives the rain process timeline
	YearFraction float64 // [0,1) from worldtime.Clock.YearFraction — drives the ANNUAL Temperature cycle (CA1)
}

// Transition is one climate cell crossing a terrain threshold this step. world maps
// Cell → []navmap.Cell and calls navmap.SetTerrain(those, To) in the apply phase.
type Transition struct {
	Cell GridCell
	From navTerrainID
	To   navTerrainID
}

// GridCellState is a cell index paired with its CellState, returned by Cells().
type GridCellState struct {
	Cell  GridCell
	State CellState
}

// State is the whole climate field for one run: the coarse grid of CellState, the rain-process
// accumulator, and the current world-uniform Wind (CA2). Snapshot-serializable (data-contracts §6).
// Bounds + cell size come from Config; world maps GridCell → []navmap.Cell when applying transitions.
// Fields are unexported (opaque); use Cells/Rain/Wind/CellAt to read.
type State struct {
	cells [][]CellState // [row=y][col=x], iterated in Y-major then X order (D12)
	rain  RainProcess
	wind  Wind
	cfg   Config
}

// ── Construction ─────────────────────────────────────────────────────────────

// New builds the initial climate State. Every climate cell is seeded from terrainAt (called with
// the cell's continuous center position) and the InitMoisture/InitTemperature from Config.
// The initial Wind is {WindPrevailingDir, WindMagMean} — no RNG draw at construction (D12).
// terrainAt must agree with the layout navmap.New uses (same WorldMin/Max + grid dims), so the
// two grids are consistent at t=0.
func New(cfg Config, terrainAt func(core.Vec2) navTerrainID) *State {
	cellW := (cfg.WorldMax.X - cfg.WorldMin.X) / float64(cfg.GridCols)
	cellH := (cfg.WorldMax.Y - cfg.WorldMin.Y) / float64(cfg.GridRows)
	cells := make([][]CellState, cfg.GridRows)
	for y := 0; y < cfg.GridRows; y++ {
		cells[y] = make([]CellState, cfg.GridCols)
		for x := 0; x < cfg.GridCols; x++ {
			// Cell center in continuous world coordinates.
			cx := cfg.WorldMin.X + (float64(x)+cellCenterOffset)*cellW
			cy := cfg.WorldMin.Y + (float64(y)+cellCenterOffset)*cellH
			center := core.Vec2{X: cx, Y: cy}
			moisture := cfg.InitMoisture
			if cfg.InitMoistureAt != nil {
				moisture = cfg.InitMoistureAt(center)
				if moisture < moistureMin {
					moisture = moistureMin
				}
				if moisture > moistureMax {
					moisture = moistureMax
				}
			}
			cells[y][x] = CellState{
				Moisture:    moisture,
				Temperature: cfg.InitTemperature,
				Terrain:     terrainAt(center),
			}
		}
	}
	return &State{
		cells: cells,
		rain:  RainProcess{}, // fresh dry state: PRain=0, Raining=false, HoursSinceRain=0
		wind:  Wind{Dir: cfg.WindPrevailingDir, Mag: cfg.WindMagMean},
		cfg:   cfg,
	}
}

// Restore reconstructs a State from its periodic-full serialization (Cells()/Rain()/Wind(),
// data-contracts §10) — the resume counterpart to New (WI-P4 persist round-trip, D12). base
// supplies the Config (geometry + rates), which is NOT itself part of the serialized snapshot
// (persist round-trips only the dynamic per-cell/rain/wind values, mirroring how a resumed world
// re-installs the same content-derived Rules before restoring dynamic state); base is typically
// a freshly-`New`-constructed placeholder built from the SAME Config as the captured run. cells
// must cover every GridCell in [0,GridCols)×[0,GridRows) exactly once — a missing, duplicate, or
// out-of-bounds cell panics (a persist-contract bug, mirrors flora/decay unknown-id panics).
// Pure; no RNG draw.
func Restore(base *State, cells []GridCellState, rain RainProcess, wind Wind) *State {
	cfg := base.cfg
	grid := make([][]CellState, cfg.GridRows)
	filled := make([][]bool, cfg.GridRows)
	for y := range grid {
		grid[y] = make([]CellState, cfg.GridCols)
		filled[y] = make([]bool, cfg.GridCols)
	}
	for _, gcs := range cells {
		x, y := gcs.Cell.X, gcs.Cell.Y
		if x < 0 || x >= cfg.GridCols || y < 0 || y >= cfg.GridRows {
			panic(fmt.Sprintf("climate.Restore: cell %+v out of bounds (%dx%d)", gcs.Cell, cfg.GridCols, cfg.GridRows))
		}
		if filled[y][x] {
			panic(fmt.Sprintf("climate.Restore: duplicate cell %+v", gcs.Cell))
		}
		grid[y][x] = gcs.State
		filled[y][x] = true
	}
	for y := range filled {
		for x := range filled[y] {
			if !filled[y][x] {
				panic(fmt.Sprintf("climate.Restore: missing cell {%d %d}", x, y))
			}
		}
	}
	return &State{cells: grid, rain: rain, wind: wind, cfg: cfg}
}

// ── Snapshot / read API ───────────────────────────────────────────────────────

// Cells returns the coarse-grid CellState in D12-sorted (Y-major then X) GridCell order,
// for the periodic-full serialization channel (data-contracts §6).
func (s *State) Cells() []GridCellState {
	out := make([]GridCellState, 0, s.cfg.GridRows*s.cfg.GridCols)
	for y := 0; y < s.cfg.GridRows; y++ {
		for x := 0; x < s.cfg.GridCols; x++ {
			out = append(out, GridCellState{
				Cell:  GridCell{X: x, Y: y},
				State: s.cells[y][x],
			})
		}
	}
	return out
}

// Rain exposes the RainProcess for snapshot/resume + observability. Returns a read-only copy.
func (s *State) Rain() RainProcess { return s.rain }

// Wind exposes the current world-uniform Wind for snapshot/resume + as the source of §6 operands
// "wind.dir"/"wind.mag" that world adapts into consumer Contexts (fauna F33/F40). Read-only copy.
func (s *State) Wind() Wind { return s.wind }

// CellAt maps a continuous position to its coarse climate cell's CellState (CA3 read path).
// world calls it to sample an animal's local climate into the fauna animal Context.
// pos is clamped to [WorldMin,WorldMax]; the mapping uses the same Config geometry New uses.
// Read-only (D11 — an index read over continuous space, never a snap of the agent's Pos).
func (s *State) CellAt(pos core.Vec2) CellState {
	cfg := &s.cfg

	// Clamp pos to [WorldMin, WorldMax].
	x := math.Max(cfg.WorldMin.X, math.Min(pos.X, cfg.WorldMax.X))
	y := math.Max(cfg.WorldMin.Y, math.Min(pos.Y, cfg.WorldMax.Y))

	// Map to grid indices (same formula New uses for cell centers).
	w := cfg.WorldMax.X - cfg.WorldMin.X
	h := cfg.WorldMax.Y - cfg.WorldMin.Y
	col := int((x - cfg.WorldMin.X) / w * float64(cfg.GridCols))
	row := int((y - cfg.WorldMin.Y) / h * float64(cfg.GridRows))

	// Clamp to valid index range (handles edge case where pos == WorldMax exactly).
	if col < 0 {
		col = 0
	} else if col >= cfg.GridCols {
		col = cfg.GridCols - 1
	}
	if row < 0 {
		row = 0
	} else if row >= cfg.GridRows {
		row = cfg.GridRows - 1
	}

	return s.cells[row][col]
}
