package rng

import (
	"encoding/json"
	"math"
	"os"
	"strings"
	"testing"
)

const goldenStateRestorePath = "testdata/golden/state_restore/seed1234_post_restore.json"

// goldenFloat64Seed42 is the expected sequence of 20 Float64() calls from New(42).
// Generated by running the test with -update and pinned here for regression detection.
var goldenFloat64Seed42 = []float64{
	0.25335066677989804,
	0.5445773428118597,
	0.1295216259328179,
	0.2658705277527088,
	0.7533127188031444,
	0.17909121180177456,
	0.09955357738929616,
	0.7970015804874262,
	0.04068546818086116,
	0.33208129776300466,
	0.8634599945543746,
	0.4355696610847959,
	0.6094005552217965,
	0.1091930936657578,
	0.8792668690746638,
	0.9073439245004071,
	0.3942566119474973,
	0.22966597506366626,
	0.9428151133241364,
	0.8817445619156224,
}

// TestGoldenSequence verifies New(42) produces the pinned Float64 sequence.
func TestGoldenSequence(t *testing.T) {
	r := New(42)
	for i, want := range goldenFloat64Seed42 {
		got := r.Float64()
		if got != want {
			t.Errorf("Float64()[%d]: got %v, want %v", i, got, want)
		}
	}
}

// TestStateRestoreRoundTrip verifies draw-50 / capture / draw-50 / restore / draw-50
// produces identical second and third batches, and that the post-restore sequence
// matches the pinned golden file (testdata/golden/state_restore/seed1234_post_restore.json).
// To regenerate the golden file, delete it and run with -update (not yet wired; delete + repin manually).
func TestStateRestoreRoundTrip(t *testing.T) {
	r := New(1234)

	// Burn 50 values.
	for i := 0; i < 50; i++ {
		r.Float64()
	}

	// Capture state, then draw batch A.
	s := r.State()
	batchA := make([]float64, 50)
	for i := range batchA {
		batchA[i] = r.Float64()
	}

	// Restore and draw batch B — must equal batch A.
	r.Restore(s)
	batchB := make([]float64, 50)
	for i := range batchB {
		batchB[i] = r.Float64()
	}

	for i := range batchA {
		if batchA[i] != batchB[i] {
			t.Errorf("batch mismatch at index %d: A=%v B=%v", i, batchA[i], batchB[i])
		}
	}

	// Compare batch B against the pinned golden file (regression guard).
	raw, err := os.ReadFile(goldenStateRestorePath)
	if err != nil {
		t.Fatalf("read golden file %s: %v", goldenStateRestorePath, err)
	}
	var golden []float64
	if err := json.Unmarshal(raw, &golden); err != nil {
		t.Fatalf("parse golden file: %v", err)
	}
	if len(golden) != len(batchB) {
		t.Fatalf("golden length %d != batch length %d", len(golden), len(batchB))
	}
	for i := range golden {
		if golden[i] != batchB[i] {
			t.Errorf("golden mismatch at index %d: got %v, want %v", i, batchB[i], golden[i])
		}
	}
}

// TestIntnRange verifies Intn(n) stays in [0, n) for various n.
func TestIntnRange(t *testing.T) {
	cases := []int{1, 10, 1000}
	r := New(99)
	for _, n := range cases {
		for i := 0; i < 1000; i++ {
			v := r.Intn(n)
			if v < 0 || v >= n {
				t.Errorf("Intn(%d) = %d, out of [0, %d)", n, v, n)
			}
		}
	}
}

// TestShufflePermutation verifies Shuffle produces a valid permutation over 100 runs.
func TestShufflePermutation(t *testing.T) {
	r := New(777)
	const size = 10
	for run := 0; run < 100; run++ {
		s := make([]int, size)
		for i := range s {
			s[i] = i
		}
		r.Shuffle(size, func(i, j int) { s[i], s[j] = s[j], s[i] })

		seen := make([]bool, size)
		for _, v := range s {
			if v < 0 || v >= size {
				t.Errorf("run %d: value %d out of range", run, v)
				continue
			}
			if seen[v] {
				t.Errorf("run %d: duplicate value %d", run, v)
			}
			seen[v] = true
		}
		for i, ok := range seen {
			if !ok {
				t.Errorf("run %d: missing value %d", run, i)
			}
		}
	}
}

// TestNormFloat64Distribution verifies mean ≈ 0 and stddev ≈ 1 over 10 000 draws.
func TestNormFloat64Distribution(t *testing.T) {
	const n = 10_000
	r := New(31415)
	sum := 0.0
	for i := 0; i < n; i++ {
		sum += r.NormFloat64()
	}
	mean := sum / n

	r2 := New(31415)
	sumSq := 0.0
	for i := 0; i < n; i++ {
		v := r2.NormFloat64() - mean
		sumSq += v * v
	}
	stddev := math.Sqrt(sumSq / n)

	if math.Abs(mean) > 0.05 {
		t.Errorf("NormFloat64 mean = %v, want |mean| < 0.05", mean)
	}
	if math.Abs(stddev-1.0) > 0.05 {
		t.Errorf("NormFloat64 stddev = %v, want |stddev-1| < 0.05", stddev)
	}
}

// TestRNGStateJSONRoundTrip verifies State() → json.Marshal → json.Unmarshal → Restore
// → next draw equals the expected next draw.
func TestRNGStateJSONRoundTrip(t *testing.T) {
	r := New(8888)
	for i := 0; i < 30; i++ {
		r.Float64()
	}

	// Capture state.
	s := r.State()

	// Marshal + unmarshal.
	raw, err := json.Marshal(s)
	if err != nil {
		t.Fatalf("json.Marshal: %v", err)
	}
	var s2 RNGState
	if err := json.Unmarshal(raw, &s2); err != nil {
		t.Fatalf("json.Unmarshal: %v", err)
	}

	// Record expected next draw without restoring.
	want := r.Float64()

	// Restore from the JSON-round-tripped state and draw.
	r.Restore(s2)
	got := r.Float64()

	if got != want {
		t.Errorf("after JSON round-trip: got %v, want %v", got, want)
	}
}

// TestNoForbiddenImports checks that rng.go does not import "time" or use
// the global rand functions (no bare rand.Float64, rand.Intn, etc.).
func TestNoForbiddenImports(t *testing.T) {
	src, err := os.ReadFile("rng.go")
	if err != nil {
		t.Fatalf("os.ReadFile(rng.go): %v", err)
	}
	content := string(src)

	if strings.Contains(content, `"time"`) {
		t.Error(`rng.go must not import "time"`)
	}
	// Global rand calls in math/rand/v2 would look like rand.Float64() — the package-level func.
	// Our wrapper only calls methods on r.r (a *rand.Rand value), so we check for
	// the global-call pattern: "rand.Float64()" / "rand.Intn(" / "rand.NormFloat64()" etc.
	globalCalls := []string{
		"rand.Float64()",
		"rand.Intn(",
		"rand.NormFloat64()",
		"rand.Shuffle(",
		"rand.IntN(",
	}
	for _, g := range globalCalls {
		if strings.Contains(content, g) {
			t.Errorf("rng.go must not use global rand call %q", g)
		}
	}
}
